enableInlineBuilds: true

lockfileFilename: public-yarn.lock

nodeLinker: node-modules

npmAuthToken: sr8yMiDOGOGgbLKyquniig==

npmRegistryServer: "http://127.0.0.1:4873"

unsafeHttpWhitelist:
  - localhost
  - 127.0.0.1

yarnPath: .yarn/releases/yarn-3.5.0.cjs
